import { Building2, ChevronRight, Network, Plus, Search, Settings2, ShieldCheck, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Drawer, Metric, PageHead, Panel, Status, TreeNode } from "@/components/ui/ToolKit";
import { departments, orgUnits, partners, people } from "@/lib/staticData";

const sections=[
 {key:"overview",label:"Overview",icon:Settings2},
 {key:"people",label:"People & Access",icon:Users},
 {key:"roles",label:"Roles & Permissions",icon:ShieldCheck},
 {key:"units",label:"Organization Units",icon:Building2},
 {key:"departments",label:"Departments",icon:Network},
 {key:"partners",label:"Partner Directory",icon:Network},
] as const;
export function WorkspaceSettingsPage(){const nav=useNavigate();const {settingsSection}=useParams();const current=settingsSection&&sections.some(s=>s.key===settingsSection)?settingsSection:"overview";return <div className="page"><PageHead eyebrow="Workspace / Administration" title="Organization Settings" description="Manage tenant administration through permission-aware working surfaces. The navigation is stable; each section uses the interaction pattern best suited to its data."/><div style={{display:"grid",gridTemplateColumns:"210px minmax(0,1fr)",gap:10,alignItems:"start"}}><aside className="panel" style={{position:"sticky",top:0}}><div className="panel-head"><div><div className="panel-kicker">Kumar Constructions</div><div className="panel-title">Settings</div></div></div><div className="panel-body" style={{padding:7}}>{sections.map(s=><button key={s.key} className={`nav-item ${current===s.key?"active":""}`} style={{width:"100%"}} onClick={()=>nav(`/workspace/settings/${s.key}`)}><s.icon/><span>{s.label}</span><ChevronRight size={12} style={{marginLeft:"auto"}}/></button>)}</div></aside><main><SettingsSection section={current}/></main></div></div>}
function SettingsSection({section}:{section:string}){if(section==="people")return <PeopleSection/>;if(section==="roles")return <RolesSection/>;if(section==="units")return <UnitsSection/>;if(section==="departments")return <DepartmentsSection/>;if(section==="partners")return <PartnersSection/>;return <Overview/>}
function Overview(){return <><div className="metric-grid"><Metric label="Members" value="86" foot="81 active / 5 invited"/><Metric label="Custom roles" value="11" foot="Across organization + modules"/><Metric label="Organization units" value="6" foot="3 hierarchy levels"/><Metric label="Partners" value="14" foot="8 active on projects"/></div><div className="split"><div style={{display:"grid",gap:10}}><Panel title="Administration readiness" kicker="Organization health"><div className="timeline">{["Organization identity complete","9 modules enabled","Primary owner active","Role model configured","Project access rules active"].map((x,i)=><div className="timeline-item" key={x}><div className="timeline-mark"/><div className="timeline-copy"><strong>{x}</strong><span>{i<4?"Configuration is complete and available to the workspace.":"2 project-level assignments changed this week."}</span></div></div>)}</div></Panel><Panel title="Recent administration activity" kicker="Audit preview"><table className="data-table"><tbody><tr><td className="ref">00:18</td><td><strong>Project Manager role updated</strong></td><td>Vasi Sayed</td></tr><tr><td className="ref">YESTERDAY</td><td><strong>Neha Patil added to Skyline Tower</strong></td><td>Aisha Shaikh</td></tr><tr><td className="ref">12 AUG</td><td><strong>Partner contact changed</strong></td><td>Rohan Mehta</td></tr></tbody></table></Panel></div><Panel title="Access posture" kicker="Inspector" className="inspector"><div className="inspector-section"><div className="inspector-label">Current admin role</div><strong>Organization Admin</strong><div className="ref" style={{marginTop:3}}>ORG_TOP / KUMAR</div></div><div className="inspector-section"><div className="inspector-label">Visible sections</div><div className="inspector-value">All six administration sections are visible in this static prototype. In production, each section is hidden unless the active role has the corresponding view permission.</div></div><div className="inspector-section"><Status tone="green">Permission context healthy</Status></div></Panel></div></>}
function PeopleSection(){const [q,setQ]=useState("");const [sel,setSel]=useState(0);const [drawer,setDrawer]=useState(false);const filtered=useMemo(()=>people.filter(x=>(x.name+x.email+x.role+x.scope).toLowerCase().includes(q.toLowerCase())),[q]);const p=people[sel]||people[0];return <><div className="toolbar"><div className="searchbox"><Search/><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search people…"/></div><div className="grow"/><button className="btn primary" onClick={()=>setDrawer(true)}><Plus size={13}/> Add member</button></div><div className="split wide-inspector"><Panel title="Organization members" kicker={`${filtered.length} visible`}><table className="data-table"><thead><tr><th>User</th><th>Role</th><th>Scope</th><th>Last active</th><th>Status</th></tr></thead><tbody>{filtered.map(x=>{const i=people.findIndex(p=>p.email===x.email);return <tr key={x.email} className={sel===i?"selected":""} onClick={()=>setSel(i)}><td><strong>{x.name}</strong><div className="faint" style={{fontSize:9}}>{x.email}</div></td><td>{x.role}</td><td>{x.scope}</td><td>{x.last}</td><td><Status tone={x.status==="Active"?"green":"amber"}>{x.status}</Status></td></tr>})}</tbody></table></Panel><Panel title={p.name} kicker="Member inspector" className="inspector"><div className="inspector-section"><dl className="keyvals"><dt>Email</dt><dd>{p.email}</dd><dt>Top role</dt><dd>{p.role}</dd><dt>Scope</dt><dd>{p.scope}</dd><dt>Status</dt><dd><Status tone={p.status==="Active"?"green":"amber"}>{p.status}</Status></dd></dl></div><div className="inspector-section"><div className="inspector-label">Account actions</div><div style={{display:"grid",gap:6}}><button className="btn">Edit membership</button><button className="btn">Reset password</button><button className="btn danger">Deactivate member</button></div></div></Panel></div>{drawer?<Drawer title="Add organization member" onClose={()=>setDrawer(false)} footer={<><button className="btn" onClick={()=>setDrawer(false)}>Cancel</button><button className="btn primary" onClick={()=>setDrawer(false)}>Send invitation</button></>}><div className="field"><label>Email</label><input className="input"/></div><div className="field" style={{marginTop:12}}><label>Initial top role</label><select className="select"><option>Project Manager</option><option>Site Engineer</option><option>Viewer</option></select></div></Drawer>:null}</>}
function RolesSection(){const roles=["Organization Admin","Project Manager","Quality Manager","Site Engineer","Viewer"];const perms=["View","Create","Update","Delete","Approve","Share","Admin"];const [matrix,setMatrix]=useState(()=>roles.map((_,r)=>perms.map((_,c)=>r===0||c<Math.max(1,6-r))));return <div className="split wide-inspector"><Panel title="Roles & permissions" kicker="Permission matrix"><div className="callout"><ShieldCheck size={14}/> Permissions are grouped by enabled modules in production. This compact matrix demonstrates the interaction without burying users in one permission card per code.</div><div style={{overflow:"auto",marginTop:12}}><table className="data-table"><thead><tr><th>Role</th>{perms.map(p=><th key={p}>{p}</th>)}</tr></thead><tbody>{roles.map((r,ri)=><tr key={r}><td><strong>{r}</strong></td>{perms.map((p,pi)=><td key={p}><button onClick={()=>setMatrix(m=>m.map((row,ridx)=>row.map((v,cidx)=>ridx===ri&&cidx===pi?!v:v)))} style={{width:22,height:22,border:"1px solid var(--line)",background:matrix[ri][pi]?"var(--brand)":"var(--surface)",color:"#fff"}}>{matrix[ri][pi]?"✓":""}</button></td>)}</tr>)}</tbody></table></div></Panel><Panel title="Project Manager" kicker="Role inspector" className="inspector"><div className="inspector-section"><dl className="keyvals"><dt>Role type</dt><dd>Organization top role</dd><dt>Assignments</dt><dd>8 users</dd><dt>Scope model</dt><dd>Org / unit / project</dd><dt>Module access</dt><dd>Project, Checklist, Snag</dd></dl></div><div className="inspector-section"><button className="btn primary" style={{width:"100%"}}>Save role permissions</button></div></Panel></div>}
function UnitsSection(){const [sel,setSel]=useState(1);const n=orgUnits[sel];return <div className="three-pane" style={{minHeight:540}}><section className="pane"><div className="pane-head"><div className="panel-title">Organization units</div><button className="act">+ UNIT</button></div><div className="pane-scroll"><div className="tree">{orgUnits.map((x,i)=><TreeNode key={x.code} label={x.name} code={x.code} depth={x.depth} selected={sel===i} onClick={()=>setSel(i)}/>)}</div></div></section><section className="pane"><div className="pane-head"><div><div className="panel-kicker">Selected unit</div><div className="panel-title">{n.name}</div></div></div><div className="pane-scroll"><div className="form-grid"><div className="field"><label>Unit name</label><input className="input" defaultValue={n.name}/></div><div className="field"><label>Type</label><input className="input" defaultValue={n.type}/></div><div className="field"><label>Projects</label><input className="input" defaultValue={String(n.projects)}/></div><div className="field"><label>Members in scope</label><input className="input" defaultValue={String(n.users)}/></div></div></div></section><aside className="pane"><div className="pane-head"><div className="panel-title">Inspector</div></div><div className="inspector-section"><dl className="keyvals"><dt>Reference</dt><dd className="ref">{n.code}</dd><dt>Depth</dt><dd>{n.depth}</dd><dt>Status</dt><dd><Status tone="green">Active</Status></dd></dl></div></aside></div>}
function DepartmentsSection(){return <div className="split"><Panel title="Departments" kicker="Functional structure"><table className="data-table"><thead><tr><th>Department</th><th>Lead</th><th>Units</th><th>Members</th></tr></thead><tbody>{departments.map(x=><tr key={x.code}><td><div className="ref">{x.code}</div><strong>{x.name}</strong></td><td>{x.lead}</td><td>{x.units}</td><td>{x.members}</td></tr>)}</tbody></table></Panel><Panel title="Department rules" kicker="Inspector"><div className="callout">Departments are functional structures and remain separate from Organization Units. Assign them to one or more units instead of forcing them into the geographic/legal hierarchy.</div></Panel></div>}
function PartnersSection(){return <div className="split"><Panel title="Partner directory" kicker="External organizations"><table className="data-table"><thead><tr><th>Partner</th><th>Type</th><th>Primary contact</th><th>Projects</th></tr></thead><tbody>{partners.map(x=><tr key={x.code}><td><div className="ref">{x.code}</div><strong>{x.name}</strong></td><td>{x.type}</td><td>{x.contact}</td><td>{x.projects}</td></tr>)}</tbody></table></Panel><Panel title="Partner participation" kicker="Inspector"><div className="callout">Partner organization identity, contacts, project participation and partner-scoped roles remain distinct concepts. This prevents external access from leaking beyond intended projects/modules.</div></Panel></div>}
