import { ArrowRight, Building2, ShieldCheck, Wrench } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";

export function LoginPage() {
  const navigate=useNavigate(); const [email,setEmail]=useState("superadmin@siteos.app"); const [org,setOrg]=useState("");
  const login=(target:string)=>navigate(target);
  return <div className="login-page"><section className="login-brand"><div><div style={{display:"flex",alignItems:"center",gap:10}}><div className="brand-mark" style={{background:"#fff",color:"var(--brand)"}}>SO</div><strong>SiteOS</strong><span style={{opacity:.5}}>/</span><span style={{fontSize:11,opacity:.78}}>Construction Operating Platform</span></div><h1>One workspace for the paperwork the site runs on.</h1><p>Control organizations, projects, inspections, approvals, snags and documents with clear ownership, traceable decisions and a structure teams can actually work in every day.</p><div className="login-points"><div className="login-point"><ShieldCheck size={18}/><strong style={{marginTop:10}}>Controlled</strong><span>Permissions and access follow the active organization, role and project context.</span></div><div className="login-point"><Building2 size={18}/><strong style={{marginTop:10}}>Structured</strong><span>Physical hierarchy, execution stages and project modules stay aligned.</span></div><div className="login-point"><Wrench size={18}/><strong style={{marginTop:10}}>Operational</strong><span>Built like a working tool, not a marketing dashboard.</span></div></div></div><div style={{font:"500 9px 'IBM Plex Mono'",opacity:.7}}>SITEOS / STATIC UX PROTOTYPE / AUG 2026</div></section><section className="login-form-wrap"><div className="login-card"><p className="eyebrow">Secure access</p><h2>Sign in to SiteOS</h2><p>This static redesign lets you enter either the platform console or a tenant workspace without a backend connection.</p><div className="login-fields"><div className="field"><label>Organization ID <span style={{fontFamily:"inherit",textTransform:"none",letterSpacing:0}}>(tenant users)</span></label><input className="input" value={org} onChange={e=>setOrg(e.target.value)} placeholder="ORG-8QM2K4TP"/></div><div className="field"><label>Email</label><input className="input" value={email} onChange={e=>setEmail(e.target.value)} /></div><div className="field"><label>Password</label><input className="input" type="password" defaultValue="siteos-demo"/></div><button className="btn primary" style={{height:36}} onClick={()=>login(org?"/workspace":"/")}>Sign in <ArrowRight size={14}/></button></div><div className="demo-identities"><div className="panel-kicker">Demo identities</div><button className="demo-id" onClick={()=>{setOrg("");setEmail("superadmin@siteos.app");login("/")}}><strong>Platform Superadmin</strong><span>superadmin@siteos.app · opens Platform Console</span></button><button className="demo-id" onClick={()=>{setOrg("ORG-8QM2K4TP");setEmail("vasi@kumar.example");login("/workspace")}}><strong>Organization User · Project Manager</strong><span>ORG-8QM2K4TP · opens Kumar Constructions workspace</span></button></div></div></section></div>;
}
